### ISSUE TITLE
Unexpected communications error 

### ISSUE THREAD

**Issue by Namwanza** [hashicorp/vagrant-vmware-desktop#104]
Vagrant encountered an unexpected communications error with the Vagrant VMware Utility driver.

**Comment by fourdim** [comment]
```log
INFO vmconfig: config class lookup for provider :vmware_workstation gave us base class: HashiCorp::VagrantVMwareDesktop::Config  
 INFO vmconfig: config class lookup for provider :vmware_desktop gave us base class: HashiCorp::VagrantVMwareDesktop::Config      
 INFO vmconfig: looking up provider config for: :vmware_desktop
 INFO vmconfig: provider config value that was stored: #<HashiCorp::VagrantVMwareDesktop::Config:0x000001e2df289380 @allowlist_verified=true, @base_address=nil, @base_mac=nil, @clone_directory=nil, @functional_hgfs=true, @unmount_default_hgfs=true, @enable_vmrun_ip_lookup=true, @gui=false, @force_vmware_license=nil, @linked_clone=true, @nat_device=nil, @network_adapters={0=>[:nat, {:auto_config=>false}]}, @shared_folder_special_char="-", @verify_vmnet=true, @vmx={"cpuid.coresPerSocket"=>"1", "memsize"=>"4096", "numvcpus"=>"2"}, @port_forward_network_pause=0, @ssh_info_public=false, @utility_host="127.0.0.1", @utility_port=9922, @utility_certificate_path="C:/ProgramData/HashiCorp/vagrant-vmware-desktop/certificates", @logger=#<Log4r::Logger:0x000001e2df134e58 @fullname="hashicorp::provider::vmware::config", @outputters=[], @additive=true, @name="config", @path="hashicorp::provider::vmware", @parent=#<Log4r::Logger:0x000001e2df134598 @fullname="hashicorp", @outputters=[#<Log4r::StderrOutputter:0x000001e2ddf073e8 @name="stderr", @level=0, @formatter=#<Vagrant::Util::LoggingFormatter:0x000001e2de25b3a0 @formatter=#<Log4r::BasicFormatter:0x000001e2de2abe18 
@depth=7>>, @out=#<IO:<STDERR>>>], @additive=true, @name="hashicorp", @path="", @parent=#<Log4r::RootLogger:0x000001e2ddab4160 @level=0, @outputters=[]>, @level=2, @trace=false>, @level=2, @trace=false>, @__invalid_methods=#<Set: {}>>
 INFO machine: Initializing machine: default
 INFO machine:   - Provider: HashiCorp::VagrantVMwareDesktop::Provider
 INFO machine:   - Box: #<Vagrant::Box:0x000001e2dfba9e60>
 INFO machine:   - Data dir: D:/vagrant/debian11/.vagrant/machines/default/vmware_desktop
DEBUG vmware: Re-initializing driver for new ID: "D:/vagrant/debian11/.vagrant/machines/default/vmware_desktop/b63d5d29-2d8c-472c-9b92-164b9367a0fb/generic-debian11-vmware.vmx"
 INFO vmware_driver: VMX file: D:/vagrant/debian11/.vagrant/machines/default/vmware_desktop/b63d5d29-2d8c-472c-9b92-164b9367a0fb/generic-debian11-vmware.vmx
DEBUG vagrant_utility: initialize HOST=127.0.0.1 PORT=9922
DEBUG checkpoint_client: utility communication error - Vagrant encountered an unexpected communications error with the
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x000001e2df134200>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<HashiCorp::VagrantVMwareDesktop::Errors::DriverAPIRequestUnexpectedError: Vagrant encountered an unexpected communications error with the
ERROR vagrant: C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/helper/vagrant_utility.rb:182:in `rescue in process_response'
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/helper/vagrant_utility.rb:161:in `process_response'
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/helper/vagrant_utility.rb:147:in `perform_request'
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/helper/vagrant_utility.rb:104:in `get'
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/driver/base.rb:1310:in `set_vmware_info'
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/driver/base.rb:172:in `initialize'
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/driver.rb:14:in `new'
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/driver.rb:14:in `create'      
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/provider.rb:35:in `machine_id_changed'
C:/Users/masked/.vagrant.d/gems/3.1.3/gems/vagrant-vmware-desktop-3.0.3/lib/vagrant-vmware-desktop/provider.rb:18:in `initialize'

```

**Comment by fourdim** [comment]
I've found the solution. It's needed to start the service of vagrant-vmware-utility mannually (in the windows service). This is kind of frustrating.

**Comment by Lazza** [comment]
In my case **I needed to delete the following folder:**

    C:\ProgramData\hashicorp\vagrant-vmware-desktop\settings

**Comment by oferchen** [comment]
MacOS Sonoma 14.4.1 with Apple Silicon
installed vagrant-vmware-utility using brew and resolved the issue using the following commands
```
sudo launchctl unload -w /Library/LaunchDaemons/com.vagrant.vagrant-vmware-utility.plist
sudo launchctl load -w /Library/LaunchDaemons/com.vagrant.vagrant-vmware-utility.plist
```
