### ISSUE TITLE
macOs Sonoma can't install vagrant plugin, received 400 Bad Request. 

### ISSUE THREAD

**Issue by karination** [hashicorp/vagrant-vmware-desktop#109]
### Vagrant version
Vagrant 2.4.0

### Vagrant VMware utility version
1.0.22

### Host operating system
macOs Sonoma 14.1.1

### Steps to reproduce
1. Install vagrant  `brew install --cask vagrant`
2. Install vagrant-vmware-utility `brew --cask  vagrant-vmware-utility`
3. Install vagrant-vmware-desktop plugin `vagrant plugin install vagrant-vmware-desktop`

### Debug output
```
INFO global: Vagrant version: 2.4.0
 INFO global: Ruby version: 3.1.4
 INFO global: RubyGems version: 3.3.26
 INFO global: VAGRANT_INSTALLER_ENV="1"
 INFO global: VAGRANT_EXECUTABLE="/opt/vagrant/embedded/gems/gems/vagrant-2.4.0/bin/vagrant"
 INFO global: VAGRANT_INSTALLER_VERSION="2"
 INFO global: VAGRANT_INSTALLER_EMBEDDED_DIR="/opt/vagrant/embedded"
 INFO global: VAGRANT_NO_PLUGINS="1"
 INFO global: VAGRANT_DISABLE_PLUGIN_INIT="1"
 INFO global: VAGRANT_LOG="debug"
...
DEBUG bundler: Enabling user defined remote RubyGems sources
DEBUG bundler: Enabling default remote RubyGems sources
DEBUG bundler: Adding source - https://gems.hashicorp.com/
DEBUG bundler: Adding source - https://rubygems.org/
ERROR warden: Error occurred: 400 "Bad Request"
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<VagrantPlugins::CommandPlugin::Action::InstallGem:0x0000000111df94b0>
 INFO warden: Recovery complete.
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000111e902c0>
/opt/vagrant/embedded/lib/ruby/3.1.0/net/http/response.rb:142:in `error!': 400 "Bad Request" (Net::HTTPClientException)
	from /opt/vagrant/embedded/lib/ruby/3.1.0/net/http/response.rb:151:in `value'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/net/http.rb:1040:in `connect'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/net/http.rb:995:in `do_start'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/net/http.rb:990:in `start'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/request/http_pool.rb:43:in `setup_connection'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/request/https_pool.rb:7:in `setup_connection'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/request/http_pool.rb:39:in `make_connection'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/request/http_pool.rb:20:in `checkout'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/request.rb:129:in `connection_for'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/request.rb:188:in `perform_request'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/request.rb:154:in `fetch'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:309:in `request'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:209:in `fetch_http'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:248:in `fetch_path'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:285:in `cache_update_path'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/source.rb:187:in `load_specs'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/bundler.rb:698:in `block in validate_configured_sources!'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/source_list.rb:94:in `each'
	from /opt/vagrant/embedded/lib/ruby/3.1.0/rubygems/source_list.rb:94:in `each_source'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/bundler.rb:696:in `validate_configured_sources!'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/bundler.rb:569:in `internal_install'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/bundler.rb:358:in `install'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/plugin/manager.rb:141:in `block in install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/plugin/manager.rb:151:in `install_plugin'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/plugins/commands/plugin/action/install_gem.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/warden.rb:38:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/builder.rb:183:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/runner.rb:104:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/util/busy.rb:22:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/action/runner.rb:104:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/plugins/commands/plugin/command/base.rb:17:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/plugins/commands/plugin/command/install.rb:73:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/plugins/commands/plugin/command/install.rb:72:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/plugins/commands/plugin/command/install.rb:72:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/plugins/commands/plugin/command/root.rb:69:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/cli.rb:67:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/lib/vagrant/environment.rb:319:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-2.4.0/bin/vagrant:248:in `<main>'
```

**Comment by chrisroberts** [comment]
Apologies for the late reply. This was likely a transient issue. However, it is possible to adjust the sources used:

```
vagrant plugin install --plugin-clear-sources --plugin-source "https://rubygems.org" vagrant-vmware-desktop
```

Cheers
