### ISSUE TITLE
Error when trying to resize primary NVMe disk

### ISSUE THREAD

**Issue by eszense** [hashicorp/vagrant-vmware-desktop#133]
# Reproducing the error
1. Make a vagrant box with vmx defining a NVMe drive as the only disk
```
...
nvme0.present = "TRUE"
nvme0:0.fileName = "disk.vmdk"
nvme0:0.present = "TRUE"
```
(Without any of these lines: `scsi0.present = "FALSE"` or `scsi0:0.present = "FALSE"`)

2. Make a Vagrantfile containing `config.vm.disk` with `primary: true`
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "private_repo/ubuntu_arm64"
  config.vm.disk :disk, size: "15GB", primary: true
  config.vm.provider "vmware_desktop" do |v|
    v.linked_clone = false
  end
end
```

3. `vagrant up`

4. Error as follows
```
NoMethodError: undefined method `[]' for nil:NilClass
/src/vagrant-vmware-desktop/lib/vagrant-vmware-desktop/cap/disk.rb:118:in `block in get_disk'
```

Expected outcome:
Resize the primary NVMe disk according to the Vagrantfile

# Cause of error

This is caused by several bugs:
### 1. `get_disk()` looks up the disk_info hash table for the keys defined in `PRIMARY_DISK_SLOTS` but did not correctly handle cases where the entry itself is absent (when there is no line matching "scsi0:0.present = *" in the vmx)
https://github.com/hashicorp/vagrant-vmware-desktop/blob/66aed2dec4379e1da5feca70e9b7afb3d5bbb6bc/lib/vagrant-vmware-desktop/cap/disk.rb#L115-L119

### 2. `get_disk()` does not return the expected nil value when a primary disk is not found
Fixing Item 1 and re-run will expose another bug with the following error due to get_disk() missing a nil return.
```
TypeError: no implicit conversion of String into Integer
  /src/vagrant-vmware-desktop/lib/vagrant-vmware-desktop/cap/disk.rb:151:in `[]'
```
Expected: get_disk() returns nil when the queried disk is not found
Current:  get_disk() returns an irrelevant value `["scsi0:0", "sata0:0", "ide0:0"]` (the last evaluated statement) 
This leads to the plugin failing with error instead of creating a new disk in cases where the primary disk defined in config is not present in the vmx file

https://github.com/hashicorp/vagrant-vmware-desktop/blob/66aed2dec4379e1da5feca70e9b7afb3d5bbb6bc/lib/vagrant-vmware-desktop/cap/disk.rb#L113-L133

### 3. nvme0:0 is not in the search list of primary disk

https://github.com/hashicorp/vagrant-vmware-desktop/blob/66aed2dec4379e1da5feca70e9b7afb3d5bbb6bc/lib/vagrant-vmware-desktop/cap/disk.rb#L31
 

# Environment:
Vagrant 2.2.11.dev
VMWare Fusion 13.6.2 (MacOS)
VAGRANT_EXPERIMENTAL=disks

**Comment by wilson-conley** [comment]
I'm running into this issue as well - any updates on when the linked PR will be merged in?
