### ISSUE TITLE
vagrant up after successful provisioning fails unless folder share is removed. 

### ISSUE THREAD

**Issue by bayeslearner** [hashicorp/vagrant-vmware-desktop#39]
### Vagrant version

Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.

### Vagrant VMware plugin version
Vagrant 2.2.19

### Vagrant VMware utility version
 & 'C:\HashiCorp\VagrantVMwareUtility\bin\vagrant-vmware-utility.exe' -v
1.0.21

### Host operating system

Windows 11

### Guest operating system
Tried generic/ubuntu2004  and generic/rockylinux

### Vagrantfile

```ruby
# unless Vagrant.has_plugin?("vagrant-disksize")
#   puts 'Installing vagrant-disksize Plugin...'
#   system('vagrant plugin install vagrant-disksize')
# end
 
# unless Vagrant.has_plugin?("vagrant-vbguest")
#   puts 'Installing vagrant-vbguest Plugin...'
#   system('vagrant plugin install vagrant-vbguest')
# end
 


ENV['VAGRANT_DEFAULT_PROVIDER'] ="vmware_desktop"

unless Vagrant.has_plugin?("vagrant-hostmanager")
  puts 'Installing vagrant-hostmanager Plugin...'
  system('vagrant plugin install vagrant-hostmanager')
end

unless Vagrant.has_plugin?("vagrant-vmware-desktop")
  puts 'Installing vagrant-vmware-desktop Plugin...'
  system('vagrant plugin install vagrant-vmware-desktop')
end

NUM_CORE = 8
MEMORY = 16384
HOSTNAME = "bayes-learn"
IP_ADDR = "192.168.1.17"

Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true
  
  config.vm.box_check_update = false 
  config.vm.box = "generic/ubuntu2004"                      # select rocky8
  config.vm.provider "vmware_desktop" do |v|            # select 'vmware_desktop' as provider
    v.linked_clone = false
    v.ssh_info_public = true
    v.vmx['virtualHW.version'] = '16'                   # choose 16 as 'vmware_desktop' version
    v.vmx['mks.enable3d'] = true                        # enable 3D acceleration
    v.vmx['vmci0.present'] = true                       # enable Virtual Machine Configuration Interface
    v.vmx['hpet0.present'] = true                       # enable High Precision Event Timer
    v.vmx['virtualHW.productCompatibility'] = 'hosted'  # select 'virtualHW.productCompatibility' as 'hosted' this simply means we work with VMware Fusion, Workstation, Player etc.
    v.vmx['powerType.powerOff'] = 'soft'                # regular power settings 
    v.vmx['powerType.powerOn'] = 'soft'                 # regular power settings
    v.vmx['powerType.suspend'] = 'soft'                 # regular power settings
    v.vmx['powerType.reset'] = 'soft'                   # regular power settings
    v.vmx['guestOS'] = 'centos'                      # select 'ubuntu-64' as 'guostOS' in VMware
    v.vmx['sound.autoDetect'] = true                    # regular sound settings
    v.vmx['sound.fileName'] = '-1'                      # regular sound settings
    v.vmx['sound.present'] = true                       # regular sound settings
    v.vmx['numvcpus'] = NUM_CORE||= '8'                 # two processor cores reserved for vm
    v.vmx['cpuid.coresPerSocket'] =  1                  # one socket reserved for vm [1(socket)*2(CPU)=2(CPU)]
    v.vmx['vcpu.hotadd'] = true                         # enable VMware Hot Add for CPU              
    v.vmx['vhv.enable'] = true                         # enable nested virtulazation on vm
    v.vmx['memsize'] = MEMORY||='8192'                    # reserve 3GB RAM for vm
    v.vmx['mem.hotadd'] = true                          # enable VMWare Hot Add for RAM
    v.vmx['nvme0.present'] = true                       # select nvme for primary drive
    v.vmx['usb.present'] = true                         # enable USB controller
    v.vmx['ehci.present'] = true                        # enable USB controller
    v.vmx['svga.graphicsMemoryKB'] = '262144'           # reserve 256MB for GPU
  end

  config.vm.synced_folder '.', '/vagrant'                       # the trailing slash is needed somehow. 

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get full-upgrade -y
  #   apt-get install tasksel network-manager network-manager-gnome gdm3 open-vm-tools-desktop mate-terminal adwaita-icon-theme-full -y
  #   tasksel install ubuntu-desktop-minimal -y
  #   systemctl set-default graphical.target
  #   reboot
  # SHELL

  config.vm.hostname = (HOSTNAME||="bayes-vagrant")
  config.vm.network "public_network", ip: IP_ADDR

  # config.vm.provision "shell", reboot:true,  inline: <<-SHELL
  #   echo $(whoami)
  #   dnf update -y
  #   dnf install -y epel-release
  #   dnf install git ansible -y
  #   dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo
  #   dnf update
  #   dnf install --allowerasing -y docker-ce docker-ce-cli containerd.io
  #   usermod -aG docker vagrant
  #   systemctl enable docker
  #   dnf groupinstall -y workstation 
  #   systemctl set-default graphical.target
  #   #reboot
  # SHELL

  config.vm.provision "shell", reboot:true,  inline: <<-SHELL
    echo $(whoami)
    apt update -y
    apt upgrade -y
    apt install git ansible -y
    apt install -y apt-transport-https ca-certificates curl software-properties-common
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
    apt-cache policy docker-ce
    apt install docker-ce -y
    usermod -aG docker vagrant
    systemctl enable docker
    apt install -y --no-install-recommends ubuntu-desktop
    apt install -y chromium-browser

    #reboot
  SHELL

  config.vm.provision "shell", inline: <<-SHELL
  sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config    
  systemctl restart sshd.service
  SHELL

  config.vm.provision "shell" do |s|
    ssh_prv_key = ""
    ssh_pub_key = ""
    if File.file?("#{Dir.home}/.ssh/id_rsa")
      ssh_prv_key = File.read("#{Dir.home}/.ssh/id_rsa")
      ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
    else
      puts "No SSH key found. You will need to remedy this before pushing to the repository."
    end
    s.inline = <<-SHELL
      if grep -sq "#{ssh_pub_key}" /home/vagrant/.ssh/authorized_keys; then
        echo "SSH keys already provisioned."
        exit 0;
      fi
      echo "SSH key provisioning."
      mkdir -p /home/vagrant/.ssh/
      touch /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      echo #{ssh_pub_key} > /home/vagrant/.ssh/id_rsa.pub
      chmod 644 /home/vagrant/.ssh/id_rsa.pub
      echo "#{ssh_prv_key}" > /home/vagrant/.ssh/id_rsa
      chmod 600 /home/vagrant/.ssh/id_rsa
      chown -R vagrant:vagrant /home/vagrant
      exit 0
    SHELL
  end

  config.vm.provision "shell", privileged: false,  inline: <<-SHELL
    curl -sLS https://get.arkade.dev | sudo sh
    echo 'export PATH=$PATH:$HOME/.arkade/bin/' >> ~/.bash_profile
    git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.9.0
    echo '. $HOME/.asdf/asdf.sh' >> ~/.bashrc
    echo '. $HOME/.asdf/completions/asdf.bash' >> ~/.bashrc
    
  SHELL


end
```

### Debug output

```
Traceback (most recent call last):
        79: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        78: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `action'
        77: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:201:in `call'
        76: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
        75: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:215:in `block in action'
        74: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/machine.rb:246:in `action_raw'
        73: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
        72: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
        71: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
        70: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
        69: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        68: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/compatibility.rb:31:in `call'
        67: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        66: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        65: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        64: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/fix_old_machine_id.rb:24:in `call'
        63: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        62: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/check_vmware.rb:23:in `call'
        61: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        60: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
        59: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
        58: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
        57: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
        56: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
        55: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        54: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        53: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        52: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/compatibility.rb:14:in `call'
        51: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        50: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/fix_old_machine_id.rb:24:in `call'
        49: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        48: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/box_check_outdated.rb:23:in `call'
        47: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        46: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
        45: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
        44: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
        43: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
        42: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
        41: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        40: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        39: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        38: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/check_existing_network.rb:30:in `call'
        37: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        36: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/prune_forwarded_ports.rb:25:in `call'
        35: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        34: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/call.rb:53:in `call'
        33: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `run'
        32: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/util/busy.rb:19:in `busy'
        31: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/runner.rb:89:in `block in run'
        30: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builder.rb:149:in `call'
        29: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        28: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:127:in `block in finalize_action'
        27: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        26: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/provision.rb:80:in `call'
        25: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        24: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        23: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        22: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-hostmanager-1.8.9/lib/vagrant-hostmanager/action/update_all.rb:27:in `call'
        21: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        20: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/prepare_synced_folder_cleanup.rb:14:in `call'
        19: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        18: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/plugins/synced_folders/nfs/action_cleanup.rb:19:in `call'
        17: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        16: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in `call'
        15: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        14: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/delayed.rb:19:in `call'
        13: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        12: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/builtin/synced_folders.rb:87:in `call'
        11: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
        10: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/prepare_nfs_settings.rb:13:in `call'
         9: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/action/warden.rb:48:in `call'
         8: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/network.rb:111:in `call'
         7: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/helper/lock.rb:16:in `lock'
         6: from C:/HashiCorp/Vagrant/embedded/gems/2.2.19/gems/vagrant-2.2.19/lib/vagrant/environment.rb:614:in `lock'
         5: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/action/network.rb:113:in `block in call'
         4: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/driver/base.rb:766:in `setup_adapters'
         3: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/driver/base.rb:984:in `vmx_modify'
         2: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/driver/base.rb:984:in `open'
         1: from C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/driver/base.rb:984:in `open'
C:/Users/kunde/.vagrant.d/gems/2.7.4/gems/vagrant-vmware-desktop-3.0.1/lib/vagrant-vmware-desktop/driver/base.rb:984:in `initialize': Invalid argument @ rb_sysopen - C:/Users/kunde/Dropbox/config/config_rocky/infra_vagrant_host/.vagrant/machines/default/vmware_desktop/c8979e6b-e9ae-4bd0-9d03-17d33870ab1a/generic-ubuntu2004-vmware.vmx (Errno::EINVAL) 
```

### Expected behavior
Shouldn't throw any error.  

### Actual behavior
without commenting out   `config.vm.synced_folder '.', '/vagrant' `,  it throws exceptions. 

Sometimes it works by adding a trailing slash   config.vm.synced_folder './', '/vagrant'

**Comment by chrisroberts** [comment]
Hi there,

The cause of this issue is most likely due to where you are attempting to run Vagrant. Assuming the `C:/Users/kunde/Dropbox` folder is your dropbox synced folder, you'll want to be sure all the files expected by the Vagrantfile are synced locally and accessible. You'll also want to adjust Vagrant's dotfile path so it is not attempting to store the contents of the VM clone (or the entire VM if it is not cloned) on dropbox. You can adjust the dotfile path by setting the [VAGRANT_DOTFILE_PATH](https://developer.hashicorp.com/vagrant/docs/other/environmental-variables#vagrant_dotfile_path) environment variable. That path should be to a local directory where the local project context can be stored.

Cheers!
